### ISSUE TITLE
The Application Freezes When Trying Batch Sizes Higher Than One

### ISSUE THREAD

**Issue by Neltherion** [AbdBarho/stable-diffusion-webui-docker#12] opened 2022-08-31 11:11 UTC
Hi

I'm trying your latest version and whenever I try to use batch sizes higher than 1, the program freezes like this:

![image](https://user-images.githubusercontent.com/22426131/187664755-b12b9e26-a763-4283-aaf8-c34d7d727dee.png)

**Comment by AbdBarho** [comment] 2022-08-31 11:52
This is probably the same issue as here: https://github.com/hlky/stable-diffusion-webui/issues/337

It is part of the UI and not the docker setup, so I can't do anything about it.

**Comment by AbdBarho** [comment] 2022-08-31 15:55
@Neltherion It seems that the problem won't be fixed soon, you might want to try running again without `--optimized` or `--optimized-turbo` cli args (if it fits on you GPU), because that seems to be the cause of the problem...

**Comment by AbdBarho** [comment] 2022-09-01 04:31
@Neltherion I updated the docker image, can you try again with latest master? the problem should be fixed

**Comment by JulianKauth** [comment] 2022-09-04 09:01
Had the same issue, creating two images per batch in `--optimized-turbo`and `--optimized`works for me now.

**Comment by Neltherion** [comment] 2022-09-07 09:34
It's strange... It seems the option to pass batches is gone and I can only mention the number of images I want to generate (Max 50).

Batches were good for those who had larger VRAM.

**Comment by AbdBarho** [comment] 2022-09-07 09:52
@Neltherion Yes, unfortunately it was removed, the team was trying to optimize for low end cards.

That being said, you can try the AUTOMATIC1111 fork https://github.com/AbdBarho/stable-diffusion-webui-docker/tree/master/AUTOMATIC1111 It has the batch size parameter, and is actually much nicer.

**Closed** 2022-09-07 09:53 UTC
Labels: awaiting-response
