### ISSUE TITLE
Permission denied (13) error

### ISSUE THREAD

**Issue by shuntera** [AbdBarho/stable-diffusion-webui-docker#646] opened 2024-01-20 07:37 UTC
**Has this issue been opened before?**

- [x ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**
On running "docker-compose --profile auto-cpu up --build"
It ran for a while, then I got this error:

webui-docker-auto-cpu-1  | rsync: chown "/data/models/VAE-approx/." failed: Permission denied (13)
webui-docker-auto-cpu-1  | ./
webui-docker-auto-cpu-1  | model.pt
webui-docker-auto-cpu-1  | rsync: chown "/data/models/VAE-approx/.model.pt.UwlSvr" failed: Permission denied (13)
webui-docker-auto-cpu-1  | rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1205) [sender=3.1.3]
webui-docker-auto-cpu-1 exited with code 23

**Which UI**

auto or auto-cpu or invoke or comfy? auto-cpu

**Hardware / Software**

- OS: [e.g. Windows 10 / Ubuntu 22.04] MacOS running colima with docker
- OS version:  MacOS Sonoma 14.2.1
- WSL version (if applicable): 
- Docker Version:  Docker version 23.0.5, build bc4487a59e
- Docker compose version:  Docker Compose version 2.17.3
- Repo version:  ?
- RAM: 16GB
- GPU/VRAM: N/A

**Steps to Reproduce**

docker-compose --profile auto-cpu up --build

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by AbdBarho** [comment] 2024-02-03 07:41
Probably an edge case regarding Mac, since it is not officially supported
I don't have the hardware to develop / test on mac.
I am going to close this as duplicate of https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/35

**Closed by AbdBarho** 2024-02-03 07:41 UTC
Labels: bug
