### ISSUE TITLE
Maxing out system RAM

### ISSUE THREAD

**Issue by PassiveLemon** [AbdBarho/stable-diffusion-webui-docker#335] opened 2023-02-18 19:22 UTC
**Has this issue been opened before?**

Latest potentially related issue is #173 

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

The container slowly uses up all system RAM.

**Which UI**

Auto

**Hardware / Software**

- OS: NixOS
- OS version: 22.11
- Docker Version: 20.10.21 
- Docker compose version: 2.12.2 
- Repo version: 67c9d11 
- RAM: 32 GB
- GPU/VRAM: EVGA 3060 Ti - 8 GB GDDR6

**Steps to Reproduce**

1. Build and run the Docker container.
2. Use it for some time
3. Observe as system slows down and RAM usage reaches 99%

**Additional context**

Exit the container to close it and watch as RAM usage goes back down to normal.
Seems like the "python -u webui.py --listen --port 7860 --allow-code ..." process run by the container is what uses all of it.

**Comment by AbdBarho** [comment] 2023-02-18 21:15
duplicate of #326

**Closed by AbdBarho** 2023-02-18 21:15 UTC
Labels: bug
