### ISSUE TITLE
It looks like the config file "..." is not a valid JSON file.

### ISSUE THREAD

**Issue by SuddenDevelopment** [AbdBarho/stable-diffusion-webui-docker#44] opened 2022-09-09 18:17 UTC
I had a previous working build. I get this same error in main folder and the automatic subfolder:

```
automatic1111-model-1  |     f"It looks like the config file at '{resolved_config_file}' is not a valid JSON file."
automatic1111-model-1  | OSError: It looks like the config file at '/cache/transformers/9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.
```

**Comment by AbdBarho** [comment] 2022-09-09 18:20
@SuddenDevelopment this happens when you have an unstable connection, the download fails and shows this error.

can you clear the `cache/transformers` folder and try running again?

**Comment by SuddenDevelopment** [comment] 2022-09-09 18:22
I did, and then I also re-cloned and built fresh. I also verified same issue in the lstein folder.

I have a super fast stable connection as far as I can tell

**Comment by lucasderksen** [comment] 2022-09-09 18:29
I'm having the same error. Tried the same as SuddenDevelopment. Will try some other stuff out.

**Comment by AbdBarho** [comment] 2022-09-09 18:34
@SuddenDevelopment After clearing the cache, I managed to reproduce this issue. It seems to be part of the `transformers` library, more percisely, open ai clip.

You can in fact see for yourself that the json is not valid (extra comma)
https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/config.json

I guess it won't take much until open ai notices and fixes the problem.

In the mean time, you can manually replace the file under `cache/transformers` with the fixed one:
[file.zip](https://github.com/AbdBarho/stable-diffusion-webui-docker/files/9537914/file.zip)

**Comment by SuddenDevelopment** [comment] 2022-09-09 18:47
thanks! FYI, in the future I don;t mind helping in some way. I use this tool enough it's worth investing some time. I do know Python, web dev, docker.

**Comment by AbdBarho** [comment] 2022-09-09 18:50
@SuddenDevelopment Thank you for your offer! I will keep that in mind!

I will leave this issue open until its fixed in the open ai repo, maybe other users have the same problem.

**Closed** 2022-09-09 19:18 UTC
Labels: bug
