### ISSUE TITLE
I got an error like this

### ISSUE THREAD

**Issue by laisx** [AbdBarho/stable-diffusion-webui-docker#434] opened 2023-05-01 02:32 UTC
Attaching to webui-docker-auto-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown

**Comment by AbdBarho** [comment] 2023-05-01 05:24
duplicate of https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/406

try re-install nvidia container toolkit and try the stuff mentioned in the issue.

**Closed by AbdBarho** 2023-05-01 05:24 UTC
Labels: bug
